<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework</span></h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">ZF Skeleton Application</a>.
        You are currently running Zend Framework version <?= \Application\Module::VERSION ?>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on ZF.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zendframework" target="_blank">Fork Zend Framework on GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Feladatom</h2>
            </div>
            <div class="card-body">
                <p>
                    Feladatom egy dokumentum-kezelő rendszer elkészítése volt, amelybe hierarchikus formában feltölhetőek a dokumentumok. Mappát lehet létrehozni, törölni vagy módosítani<br>
                    Ezen felül a feltöltött dokumentumok verzió kezelését is végre hajtja egy adatbázisban. A feladattal átlagosan napi 8 órát foglalkoztam.
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Követelmények teljesítése</h2>
            </div>
            <div class="card-body">
                    <ul class="fa-ul">
                        <li><span class="fas fa-check fa-lg"> Dokumentum feltöltés  </span></li>
                        <li><span class="fas fa-check fa-lg"> Hierarhikus mappa kezelés adatbázisban  </span></li>
                        <li><span class="fas fa-check fa-lg"> Verzió kezelés </span> </li>
                        <li><span class="fas fa-check fa-lg"> Zend + Doctrine  </span> </li>
                        <li><span class="fas fa-times fa-lg"> Felhasználó kezelés </span> </li>
                    </ul>
            </div>
        </div>
    </div>
</div>
